- hosts: testserver
  become: true
  tasks:
  - name: Install multiple package
    yum: name={{item}} state=present
    loop:
     - git
     - docker
  - name: Start docker service
    service: name=docker state=started
  - name: Clone a repo from github
    git: repo=https://github.com/Sonal0409/AnsibleDockerdemo.git dest=/tmp/gitrepo
  - name: Change directory to gitrepo and build the dockerfile
    command: chdir=/tmp/gitrepo docker build -t myansibleimage .
  - name: RUn the image to create a container
    command: docker run -d -P myansibleimage

