- hosts: testserver
  become: true
  tasks:
  - name: Install multiple package
    yum: name={{item}} state=present
    loop:
     - git
     - docker
  - name: Start docker service
    service: name=docker state=started
  - name: Run the image to create a container
    command: docker run -d -P mrtienvu/endprojectimage:latest

